name: drinks_everywhere
version: 1.0.0+1
publish_to: none
description: Projeto Flutter desenvolvido para a máteria de Aplicações Hibridas com Flutter - FIAP
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  flutter_svg: any


flutter: 
  uses-material-design: true

  assets:
  - assets/
  - assets/images/

