name: drinks_everywhere
version: 1.0.0+1
publish_to: none
description: Projeto Flutter desenvolvido para a máteria de Aplicações Hibridas com Flutter - FIAP
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  font_awesome_flutter: ^9.1.0
  flutter_svg: any
  retrofit: any
  dio: 4.0.0
  cached_network_image: any
  firebase_auth: ^3.3.9
  get_storage: ^2.0.3
  flutter:
    sdk: flutter
  firebase_core: ^1.13.1

dev_dependencies:
  flutter_lints: ^1.0.0
  retrofit_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

